//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasualWorker
    {
        public int CasualWorker_id { get; set; }
        public string CS_Name { get; set; }
        public string Duty { get; set; }
    }
}
