//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Diagnostics
    {
        public int Diagnostic_id { get; set; }
        public string Patient_id { get; set; }
        public string Diagnosis { get; set; }
        public string Doctor_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
